# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "devel", "stage" ]
  pull_request:
    branches: [ "main", "devel", "stage" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 15.x
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@master
        with:
          node-version: 15.x
      - name: npm install(ing)
        run: npm install # or yarn install
      - name: Eslinter
        run: npm run lint
      - name: Install Prettier
        run: npm install prettier
      - name: Prettier
        run: npm run prettier
      - name: Jest - Test
        run: npm run test
      - name: Npm run build
        run: npm run build
