# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "dev", "stage" ]
  pull_request:
    branches: [ "main", "dev", "stage" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@master
        with:
          node-version: 15.x
      - name: npm install(ing)
        run: npm install # or yarn install
      - name: Eslinter
        run: npm run lint
      - name: Install Prettier
        run: npm install prettier
      - name: Prettier
        run: npm run prettier
      - name: Jest - Test
        run: npm run test
      - name: Npm run build
        run: npm run build
#      - name: Eslinter
#        run: npm ci # or yarn install
#      - uses: sibiraj-s/action-eslint@v2
#        with:
#          # github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
#          eslint-args: '--ignore-path=.gitignore --quiet'
#          extensions: 'js,jsx,ts,tsx'
#          annotations: true
#      - name: Prettier
#        run: npx prettier --write **/*.js3
